
DROP DATABASE IF EXISTS MLR4;
CREATE DATABASE IF NOT EXISTS MLR4;
USE MLR4;

-- Table parent : PERSONNES
CREATE TABLE PERSONNES (
  ID_PERSONNE BIGINT(4) NOT NULL PRIMARY KEY,
  NOM_PERSONNE CHAR(255) NOT NULL,
  PRENOM_PERSONNE CHAR(255) NOT NULL,
  TELEPHONE_PERSONNE BIGINT(4) NOT NULL,
  EMAIL_PERSONNE VARCHAR(255) NOT NULL
);

-- Table : CLIENTS
CREATE TABLE CLIENTS (
  ID_PERSONNE BIGINT(4) NOT NULL PRIMARY KEY,
  ADRESSE_CLIENT VARCHAR(255) NOT NULL,
  FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNES(ID_PERSONNE)
);

-- Table : EMPLOYES
CREATE TABLE EMPLOYES (
  ID_PERSONNE BIGINT(4) NOT NULL PRIMARY KEY,
  ID_STUDIO BIGINT(4) NOT NULL,
  POSTE_EMPLOYES CHAR(255) NOT NULL,
  FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNES(ID_PERSONNE),
  FOREIGN KEY (ID_STUDIO) REFERENCES STUDIOS(ID_STUDIO)
);

-- Table : PHOTOGRAPHES
CREATE TABLE PHOTOGRAPHES (
  ID_PERSONNE BIGINT(4) NOT NULL PRIMARY KEY,
  SPECIALISATION_PHOTOGRAPHE CHAR(255) NOT NULL,
  EXPERIENCE_PHOTOGRAPHE VARCHAR(255) NOT NULL,
  FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNES(ID_PERSONNE)
);

-- Table : VIDEOGRAPHES
CREATE TABLE VIDEOGRAPHES (
  ID_PERSONNE BIGINT(4) NOT NULL PRIMARY KEY,
  ID_EQUIPEMENT BIGINT(4) NOT NULL,
  SPECIALISATION_VIDEOGRAPHE VARCHAR(255) NOT NULL,
  EXPERIENCE_VIDEOGRAPHE VARCHAR(255) NOT NULL,
  FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNES(ID_PERSONNE),
  FOREIGN KEY (ID_EQUIPEMENT) REFERENCES EQUIPEMENTS(ID_EQUIPEMENT)
);
